AWSTemplateFormatVersion: "2010-09-09"
Description: DynamoDB table for items

Resources:
  ItemsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: items
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: id
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST

Outputs:
  TableName:
    Description: DynamoDB table name
    Value: !Ref ItemsTable
    Export:
      Name: !Sub "${AWS::StackName}-TableName"

  TableArn:
    Description: DynamoDB table ARN
    Value: !GetAtt ItemsTable.Arn
    Export:
      Name: !Sub "${AWS::StackName}-TableArn"
