AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  InstanceName:
    Type: String
    Default: my-app
    Description: Name for the Lightsail instance

  BlueprintId:
    Type: String
    Default: debian_13
    Description: Lightsail blueprint (e.g., debian_12, debian_13, ubuntu_24_04)

  SyncthingBucket:
    Type: String
    Description: S3 bucket containing Syncthing cert.pem and key.pem

  GitRepo:
    Type: String
    Description: Git repository URL (e.g., https://github.com/user/repo.git)

Resources:
  Instance:
    Type: AWS::Lightsail::Instance
    Properties:
      InstanceName: !Ref InstanceName
      BlueprintId: !Ref BlueprintId
      BundleId: nano_3_0
      UserData: !Sub |
        #!/bin/bash
        set -e

        # Update system
        apt update && apt upgrade -y

        # Install unattended-upgrades for automatic security patches
        apt install -y unattended-upgrades
        cat >> /etc/apt/apt.conf.d/50unattended-upgrades <<EOF
        Unattended-Upgrade::Automatic-Reboot "true";
        Unattended-Upgrade::Automatic-Reboot-Time "03:00";
        EOF
        systemctl enable unattended-upgrades

        # Install AWS CLI for S3 access
        apt install -y awscli

        # Install Syncthing
        apt install -y syncthing
        mkdir -p /root/.config/syncthing

        # Pull Syncthing identity from S3 (keeps same device ID across rebuilds)
        aws s3 cp s3://${SyncthingBucket}/syncthing/cert.pem /root/.config/syncthing/
        aws s3 cp s3://${SyncthingBucket}/syncthing/key.pem /root/.config/syncthing/
        aws s3 cp s3://${SyncthingBucket}/syncthing/config.xml /root/.config/syncthing/ || true

        # Enable and start Syncthing
        systemctl enable syncthing@root
        systemctl start syncthing@root

        # Install Python and Flask dependencies
        apt install -y python3 python3-pip python3-venv git

        # Clone app from git
        git clone ${GitRepo} /opt/app
        cd /opt/app

        # Create virtualenv and install dependencies
        python3 -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

        # Create systemd service for the Flask app
        cat > /etc/systemd/system/myapp.service <<EOF
        [Unit]
        Description=Flask App
        After=network.target

        [Service]
        User=root
        WorkingDirectory=/opt/app
        Environment="PATH=/opt/app/venv/bin"
        Environment="DYNAMODB_TABLE=items"
        ExecStart=/opt/app/venv/bin/gunicorn -w 3 -b 0.0.0.0:5000 --access-logfile - --error-logfile - "app:create_app()"
        Restart=always
        RestartSec=5

        [Install]
        WantedBy=multi-user.target
        EOF

        # Enable and start the app
        systemctl daemon-reload
        systemctl enable myapp
        systemctl start myapp

        # Create a deploy script for updates
        cat > /opt/deploy.sh <<'DEPLOY'
        #!/bin/bash
        cd /opt/app
        git pull
        source venv/bin/activate
        pip install -r requirements.txt
        systemctl restart myapp
        DEPLOY
        chmod +x /opt/deploy.sh

  StaticIp:
    Type: AWS::Lightsail::StaticIp
    Properties:
      StaticIpName: !Sub ${InstanceName}-ip
      AttachedTo: !Ref InstanceName
    DependsOn: Instance

Outputs:
  InstanceName:
    Value: !Ref Instance
    Description: Lightsail instance name

  StaticIpAddress:
    Value: !GetAtt StaticIp.IpAddress
    Description: Static IP address - point your Route 53 A record here
